name: filemanager
services:
    tinyfilemanager:
        volumes:
            - /absolute/path:/var/www/html/data
        ports:
            - 80:80
        restart: always
        container_name: tinyfilemanager
        image: tinyfilemanager/tinyfilemanager:master
